apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "taalback.fullname" . }}
  labels: {{ include "taalback.commonLabels" . | trim | nindent 4 }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | trim | indent 4 }}
{{- end }}
data:
  {{- tpl (.Files.Glob "config/*.toml").AsConfig . | trim | nindent 2 }}
