## Image pull secrets
imagePullSecrets: []

## Extra labels to add to resources
extraLabels: {}

## taalbot configuration
taalbot:
  ## Image configuration for deployment
  image:
    registry: docker.io
    repository: specialflocon/taalbot
    pullPolicy: Always
    args: ["run"]

  ## taalbot container health check
  livenessProbe: {}
  readinessProbe: {}

  ## Resource requests and limits
  resources:
    limits:
      memory: 64Mi
      cpu: 100m
    requests:
      memory: 64Mi
      cpu: 100m

  ## Name of the secret containing taalbot secret data, as specified in the README.
  secretName: ""

  bot:
    commandPrefix: ""

  mongodb:
    address: ""
    database: ""
    username: ""
    secretName: ""
    secretPasswordKey: ""

  server:
    logChannel: ""
