apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "taalbot.fullname" . }}
  labels: {{ include "taalbot.commonLabels" . | trim | nindent 4 }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | trim | indent 4 }}
{{- end }}
spec:
  selector:
    matchLabels: {{ include "taalbot.selectorLabels" . | trim | nindent 6 }}
  template:
    metadata:
      labels: {{ include "taalbot.selectorLabels" . | trim | nindent 8 }}
    spec:
      containers:
      - name: {{ template "taalbot.name" . }}
        image: {{ template "taalbot.image" . }}
        imagePullPolicy: {{ .Values.taalbot.image.pullPolicy }}
        {{- if .Values.taalbot.image.args }}
        args:
        {{- range .Values.taalbot.image.args }}
        - {{ . }}
        {{- end }}
        {{- end }}
        env:
        {{- if .Values.taalbot.application.apiServerURL }}
        - name: TAALBOT_APPLICATION_API_SERVER_URL
          value: {{ .Values.taalbot.application.apiServerURL }}
        {{- end }}
        - name: TAALBOT_DISCORD_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.taalbot.secretName }}
              key: bot-token
        {{- if .Values.taalbot.httpClient.tls.enabled }}
        - name: TAALBOT_HTTP_CLIENT_TLS_ENABLE
          value: {{ .Values.taalbot.httpClient.tls.enabled | quote }}
        {{- end }}
        {{- if .Values.taalbot.httpClient.tls.caCert }}
        - name: TAALBOT_HTTP_CLIENT_TLS_CA_CERTIFICATE
          value: {{ .Values.taalbot.httpClient.tls.caCert }}
        {{- end }}
        {{- if .Values.taalbot.httpClient.tls.cert }}
        - name: TAALBOT_HTTP_CLIENT_TLS_CERTIFICATE
          value: {{ .Values.taalbot.httpClient.tls.cert }}
        {{- end }}
        {{- if .Values.taalbot.httpClient.tls.key }}
        - name: TAALBOT_HTTP_CLIENT_TLS_KEY
          value: {{ .Values.taalbot.httpClient.tls.key }}
        {{- end }}
        {{- if .Values.taalbot.livenessProbe }}
        livenessProbe: {{- toYaml .Values.taalbot.livenessProbe | trim | nindent 10 }}
        {{- end }}
        {{- if .Values.taalbot.readinessProbe }}
        readinessProbe: {{- toYaml .Values.taalbot.readinessProbe | trim | nindent 10 }}
        {{- end }}
        resources: {{- toYaml .Values.taalbot.resources | trim | nindent 10 }}
        {{- if .Values.taalbot.httpClient.tls.enabled }}
        volumeMounts:
        - name: taalbot-tls
          mountPath: {{ .Values.taalbot.httpClient.tls.mountPath }}
          readOnly: true
        {{- end }}
      {{- if .Values.taalbot.image.pullSecrets }}
      imagePullSecrets:
      {{- range .Values.taalbot.image.pullSecrets }}
      - name: {{ . }}
      {{- end }}
      {{- end }}
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        fsGroup: 65534
      {{- if .Values.taalbot.httpClient.tls.enabled }}
      volumes:
      - name: taalbot-tls
        secret:
          defaultMode: 0640
          secretName: {{ .Values.taalbot.httpClient.tls.secretName }}
      {{- end }}
