{{- if .Values.taalapi.service.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: taalapi
  labels: {{ include "taalapi.commonLabels" . | trim | nindent 4 }}
{{- if .Values.extraLabels }}
{{ toYaml .Values.extraLabels | trim | indent 4 }}
{{- end }}
spec:
  selector: {{ include "taalapi.selectorLabels" . | trim | nindent 4 }}
  ports:
  - name: taalapi-http
    port: {{ .Values.taalapi.service.ports.http }}
    targetPort: {{ .Values.taalapi.httpServer.socketAddress.portNumber }}
{{- end }}
