apiVersion: v1
name: taalapi
version: 0.1.0
appVersion: 0.1.0
description: Backend server for taalbot
type: application
keywords:
- bot
- discord
- language
sources:
- https://github.com/SpecialFlocon/taalbot
maintainers:
- name: SpécialFlocon
